# !!! APPLYING CONFIG CHANGES REQUIRES A SERVER RESTART !!!

raspi:
    enableCallback: false
    triggerUrl: http://127.0.0.1:5000/trigger
    
    requireAuthentication: false
    username: raspi
    password: raspiRules
    
appServer:    
    enableCallback: true
    triggerMethod: POST
    triggerUrl: http://127.0.0.1:5000/trigger
    requestTimeout: 30000 #milliseconds
    
    requireAuthentication: false
    username: server
    password: ServerRules
    
